apiVersion: v1
policies:
  - name: Default
    enabled: true
    rules:
      - identifier: CONTAINERS_MISSING_IMAGE_VALUE_VERSION
      - identifier: CONTAINERS_MISSING_MEMORY_REQUEST_KEY
      - identifier: CONTAINERS_MISSING_CPU_REQUEST_KEY
      - identifier: CONTAINERS_MISSING_MEMORY_LIMIT_KEY
      - identifier: CONTAINERS_MISSING_CPU_LIMIT_KEY
      - identifier: INGRESS_INCORRECT_HOST_VALUE_PERMISSIVE
      - identifier: SERVICE_INCORRECT_TYPE_VALUE_NODEPORT
      - identifier: CRONJOB_INVALID_SCHEDULE_VALUE
      - identifier: WORKLOAD_INVALID_LABELS_VALUE
      - identifier: WORKLOAD_INCORRECT_RESTARTPOLICY_VALUE_ALWAYS
      - identifier: CONTAINERS_MISSING_LIVENESSPROBE_KEY
      - identifier: CONTAINERS_MISSING_READINESSPROBE_KEY
      - identifier: HPA_MISSING_MINREPLICAS_KEY
      - identifier: HPA_MISSING_MAXREPLICAS_KEY
      - identifier: WORKLOAD_INCORRECT_NAMESPACE_VALUE_DEFAULT
      - identifier: DEPLOYMENT_INCORRECT_REPLICAS_VALUE
      - identifier: CRONJOB_MISSING_STARTINGDEADLINESECOND_KEY
      - identifier: K8S_DEPRECATED_APIVERSION_1.16
      - identifier: K8S_DEPRECATED_APIVERSION_1.17
      - identifier: CONTAINERS_INCORRECT_PRIVILEGED_VALUE_TRUE
      - identifier: WORKLOAD_MISSING_LABEL_OWNER_VALUE
      - identifier: DEPLOYMENT_MISSING_LABEL_ENV_VALUE
      - identifier: CONTAINERS_MISSING_IMAGE_VALUE_DIGEST
      - identifier: CRONJOB_MISSING_CONCURRENCYPOLICY_KEY
      - identifier: K8S_INCORRECT_KIND_VALUE_POD
      - identifier: CONTAINERS_INCORRECT_HOSTPID_VALUE_TRUE
      - identifier: CONTAINERS_INCORRECT_HOSTIPC_VALUE_TRUE
      - identifier: CONTAINERS_INCORRECT_HOSTNETWORK_VALUE_TRUE
      - identifier: CONTAINERS_INCORRECT_RUNASUSER_VALUE_LOWUID
      - identifier: CONTAINERS_INCORRECT_PATH_VALUE_DOCKERSOCKET
      - identifier: CONFIGMAP_CVE2021_25742_INCORRECT_SNIPPET_ANNOTATIONS_VALUE
      - identifier: INGRESS_CVE2021_25742_INCORRECT_SERVER_SNIPPET_KEY
      - identifier: CONTAINER_CVE2021_25741_INCORRECT_SUBPATH_KEY
      - identifier: ENDPOINTSLICE_CVE2021_25373_INCORRECT_ADDRESSES_VALUE
      - identifier: ARGO_WORKFLOW_INCORRECT_FAILFAST_VALUE_FALSE
      - identifier: ARGO_WORKFLOW_INCORRECT_SERVICE_ACCOUNT_NAME_VALUE_DEFAULT
      - identifier: ARGO_CONFIGMAP_MISSING_PART_OF_LABEL_VALUE_ARGOCD
      - identifier: ARGO_ROLLOUT_MISSING_PAUSE_DURATION
      - identifier: ARGO_APP_PROJECT_INCORRECT_NAMESPACE_VALUE
      - identifier: ARGO_WORKFLOW_INCORRECT_RETRY_STRATEGY_VALUE_EMPTY
      - identifier: ARGO_WORKFLOW_INCORRECT_REVISION_HISTORY_LIMIT_VALUE_0
      - identifier: ARGO_ROLLOUT_INCORRECT_SCALE_DOWN_DELAY_VALUE_BELOW_30
      - identifier: ARGO_ROLLOUT_INCORRECT_PROGRESS_DEADLINE_ABORT_VALUE_FALSE
      - identifier: ARGO_WORKFLOW_ENSURE_RETRY_ON_BOTH_ERROR_AND_TRANSIENT_ERROR
      - identifier: CONTAINERS_INCORRECT_READONLYROOTFILESYSTEM_VALUE
      - identifier: CONTAINERS_INCORRECT_KEY_HOSTPATH
      - identifier: CONTAINERS_MISSING_KEY_ALLOWPRIVILEGEESCALATION
      - identifier: CONTAINERS_INCORRECT_RESOURCES_VERBS_VALUE
      - identifier: CONTAINERS_INVALID_CAPABILITIES_VALUE
      - identifier: CONTAINERS_INCORRECT_KEY_HOSTPORT
      - identifier: CONTAINERS_INCORRECT_RUNASGROUP_VALUE_LOWGID
      - identifier: CONTAINERS_INCORRECT_RUNASNONROOT_VALUE
      - identifier: SRVACC_INCORRECT_AUTOMOUNTSERVICEACCOUNTTOKEN_VALUE
      - identifier: RESOURCE_MISSING_NAME
      - identifier: CONTAINERS_INCORRECT_INITIALDELAYSECONDS_VALUE
      - identifier: CONTAINERS_INCORRECT_PERIODSECONDS_VALUE
      - identifier: CONTAINERS_INCORRECT_TIMEOUTSECONDS_VALUE
      - identifier: CONTAINERS_INCORRECT_SUCCESSTHRESHOLD_VALUE
      - identifier: CONTAINERS_INCORRECT_FAILURETHRESHOLD_VALUE
      - identifier: CONTAINERS_MISSING_PRESTOP_KEY
