external-links-to-ignore:
  ['localhost', 'kyma.local', 'https://busola.local.kyma.dev']
files-to-ignore: ['node_modules']
timeout: 60
request-repeats: 5
files:
  - path: './busola/.github/ISSUE_TEMPLATE/security-vulnerability.md'
    config:
      internal-links-to-ignore: ['{CVSS']
      external-links-to-ignore:
        [
          'https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N',
        ]
