module-name: busola
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/busola-backend:latest
  - europe-docker.pkg.dev/kyma-project/prod/busola-web:latest
whitesource:
  language: javascript
  exclude:
    - '**/backend/config/config.yaml'
    - '**/tests/**'
