apiVersion: apps/v1
kind: Deployment
metadata:
  name: busola
  labels:
    app: busola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busola
  template:
    metadata:
      labels:
        app: busola
    spec:
      containers:
        - name: busola
          image: busola
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  optional: true
                  key: ENVIRONMENT
                  name: environment
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 21Mi
          ports:
            - containerPort: 3001
      volumes:
        - name: config
          configMap:
            optional: true
            name: busola-config
            items:
              - key: config
                path: config.yaml
