config:
  defaultStorage: localStorage
  features:
    LEGAL_LINKS:
      config:
        legal-disclosure:
          default: https://www.sap.com/corporate/en/legal/impressum.html
          de: https://www.sap.com/corporate/de/legal/impressum.html
        privacy:
          default: https://help.sap.com/viewer/82bdf2271c6041f79387c122147cf774/Cloud/en-US
        copyright:
          default: https://www.sap.com/corporate/en/legal/copyright.html
          de: https://www.sap.com/corporate/de/legal/copyright.html
        trademark:
          default: https://www.sap.com/corporate/en/legal/trademark.html
          de: https://www.sap.com/corporate/de/legal/trademark.html
    GET_HELP_LINKS:
      config:
        kyma-project-io:
          default: https://kyma-project.io
        help-sap-com:
          default: https://help.sap.com/docs/btp/sap-business-technology-platform/btp-basic-platform-concepts?locale=en-US&profile=20054071
    KUBECONFIG_ID:
      isEnabled: true
      config:
        kubeconfigUrl: /kubeconfig
    SENTRY:
      isEnabled: false
      config:
        dsn: ''
    EXTERNAL_NODES:
      isEnabled: false
      stage: SECONDARY
    HIDDEN_NAMESPACES:
      isEnabled: true
      config:
        namespaces:
          - kube-system
    EXTENSIBILITY:
      isEnabled: true
    EXTENSIBILITY_INJECTIONS:
      isEnabled: true
    EXTENSIBILITY_CUSTOM_COMPONENTS:
      isEnabled: false
    EXTENSIBILITY_WIZARD:
      isEnabled: false
    KYMA_COMPANION:
      isEnabled: false
      config:
        feedbackLink: https://sapinsights.eu.qualtrics.com/jfe/preview/previewId/1fa80b40-56c3-4b20-9902-877df3da3493/SV_dmWATTfes5SstG6?Q_CHL=preview&Q_SurveyVersionID=current
        documentationLink: https://help.sap.com/docs/btp/sap-business-technology-platform-internal/kyma-companion?locale=en-US&version=Internal&state=DRAFT
        model: 'gpt-4.1'
        queryMaxTokens: 8000
      useJoule: false
      jouleConfig:
        url: 'https://tan-eu12-ss.eu12.sapdas.cloud.sap/resources/public/webclient/bootstrap.js'
        botname: 'kyma_companion'
    GARDENER_LOGIN:
      isEnabled: false
      kubeconfig: null
    RESOURCE_VALIDATION:
      isEnabled: true
      config:
        policies:
          - Default
    CLUSTER_VALIDATION:
      isEnabled: false
    FEEDBACK:
      isEnabled: true
      config:
        link: https://sapinsights.eu.qualtrics.com/jfe/form/SV_d3UPNymSgUHAb9Y?product=SAP%20BTP,%20Kyma%20Runtime&product_filter=Kyma
    SNOW:
      isEnabled: false
    COMMUNITY_MODULES:
      isEnabled: true
