apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: busola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busola
  template:
    metadata:
      labels:
        app: busola
    spec:
      containers:
        - name: busola
          image: eu.gcr.io/kyma-project/busola-core:PR-236
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 21Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6080
            initialDelaySeconds: 10
          ports:
            - containerPort: 6080
            - containerPort: 8080
        - name: core-ui
          image: eu.gcr.io/kyma-project/busola-core-ui:PR-236
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 21Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6080
            initialDelaySeconds: 10
          ports:
            - containerPort: 6080
            - containerPort: 80
