apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: busola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busola
  template:
    metadata:
      labels:
        app: busola
    spec:
      containers:
        - name: busola
          image: eu.gcr.io/kyma-project/busola-web:PR-799
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 21Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/core/assets/config
      volumes:
        - name: config
          configMap:
            name: busola-config
            items:
              - key: config
                path: config.json
