apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: busola
  name: web
  labels:
    app: busola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busola
  template:
    metadata:
      labels:
        app: busola
    spec:
      containers:
        - name: busola
          image: wawrzyn321/single
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 150m
              memory: 30Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6080
            initialDelaySeconds: 10
          ports:
            - containerPort: 6080
            - containerPort: 8080
