kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-busola
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: busola.%DOMAIN%
      http:
        paths:
          - backend:
              service:
                name: core
                port:
                  number: 8080
            path: /(.*)
            pathType: Prefix
          - backend:
              service:
                name: backend
                port:
                  number: 3001
            path: /backend(?:/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: service-catalog
                port:
                  number: 8080
            path: /service-catalog/(.*)
            pathType: Prefix
          - backend:
              service:
                name: core-ui
                port:
                  number: 8080
            path: /core-ui/(.*)
            pathType: Prefix
