apiVersion: v1
kind: ConfigMap
metadata:
  name: pizzas
  namespace: pizzas
  labels:
    app.kubernetes.io/name: pizzas
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |
    {
      "header": [
        {
          "name": "Sauce",
          "source": "spec.sauce"
        },
        {
          "name": "Controlled By",
          "source": "spec.ownerReferences",
          "widget": "ControlledBy",
          "kindOnly": true,
          "placeholder": "---"
        },
        {
          "name": "Toppings",
          "source": "$join(spec.toppings.name, ', ')"
        },
        {
          "name": "Owner References",
          "source": "spec.ownerReferences[0]",
          "widget": "ResourceLink",
          "linkText": "Go to {{data.kind}} {{data.name}}.",
          "resource": {
            "name": "data.name",
            "namespace": "root.metadata.namespace",
            "kind": "data.kind"
          }
        }
      ],
      "body": [
        {
          "widget": "Columns",
          "children": [
            {
              "name": "Summary",
              "widget": "Panel",
              "children": [
                {
                  "name": "State",
                  "source": "status.messages[-1].state",
                  "widget": "Badge"
                },
                {
                  "name": "Message",
                  "source": "status.messages[-1].message"
                },
                { "name": "Toppings", "source": "$join(spec.toppings.name, ', ')" },
                { "name": "Toppings price", "source": "$sum(spec.toppings.price)" }
              ]
            },
            {
              "name": "Toppings",
              "source": "spec.toppings",
              "widget": "Table",
              "collapsible": [{"name": "Quantity", "source": "$item.quantity" }],
              "children": [
                { "name": "Name", "source": "$item.name", "sort": true },
                { "name": "Price ($)", "source": "$item.price",
                "sort": { "default": true, "compareFunction": "$second -$first" }
              }
              ]
            },
          ]
        },
        {
          "name": "Pizza's recipe secret",
          "widget": "ResourceList",
          "source": "$secretRecipe()",
          "sort": [
            {
              "source": "type",
              "default": true,
            },
          ],
        },
        {
          "name": "columns",
          "widget": "Columns",
          "children": [
            {
              "name": "Comments",
              "widget": "Panel",
              "children": [
                {
                  "name": "Comments",
                  "widget": "JoinedArray",
                  "source": "spec.comments",
                  "separator": " || "
                }
              ]
            },
            {
              "name": "Description",
              "widget": "Panel",
              "children": [{ "source": "spec.description" }]
            }
          ]
        }
      ],
      "resourceGraph": {
        "colorVariant": 2,
        "dataSources": [
          {
            "source": "relatedSecrets"
          },
          {
            "source": "relatedPizzaOrders"
          }
        ]
      }
    }
  form: |-
    [
      { "path": "spec.description", "widget": "Text" , "simple": true},
      { "path": "spec.sauce", "widget": "Text" , "simple": true},
      { "path": "spec.toppings", "widget": "GenericList", "simple": true},
      { "path": "spec.toppings[].name", "simple": true},
      { "path": "spec.toppings[].price", "simple": true},
      { "path": "spec.toppings[].quantity", "simple": true},
      { "path": "spec.comments", "widget": "SimpleList", "simple": true},
      {
        "path": "spec.recipeSecret",
        "widget": "Resource",
        "resource": {
          "kind": "Secret",
          "scope": "namespace",
          "namespace": "pizzas",
          "version": "v1"
        },
        "simple": true
      },
      {
      "path": "spec.ownerReferences",
      "widget": "GenericList",
      "simple": true
      },
      { "path": "spec.ownerReferences[].apiVersion", "simple": true},
      { "path": "spec.ownerReferences[].kind", "simple": true},
      { "path": "spec.ownerReferences[].name", "simple": true}
    ]
  list: |-
    [
      { "name": "Description", "source": "spec.description", "sort": { "compareFunction": "$compareStrings($first, $second)" } },
      { "name": "State", "source": "status.messages[-1].state", "widget": "Badge" },
      { "name": "Toppings price", "source": "$sum(spec.toppings.price)", "sort":{"default": true} }
    ]
  dataSources: |-
    {
      "secretRecipe": {
        "resource": {
          "kind": "Secret",
          "version": "v1",
          "namespace": "pizzas"
        },
        "filter": "$item.metadata.name = $root.spec.recipeSecret"
      },
      "relatedSecrets": {
        "resource": {
            "kind": "Secret",
            "version": "v1",
        },
        "filter": "$root.spec.recipeSecret = $item.metadata.name"
      },
      "relatedPizzaOrders": {
        "resource": {
          "kind": "PizzaOrder",
          "group": "busola.example.com",
          "version": "v1"
        },
        "filter": "$item.spec.pizzas[name = $root.metadata.name and namespace = $root.metadata.namespace]",
      }
    }
  general: |-
    {
      "resource": {
        "kind": "Pizza",
        "group": "busola.example.com",
        "version": "v1"
      },
      "name": "Pizzas",
      "category": "Lunch",
      "scope": "namespace",
      "description": "Customize the pizza view further with the Busola {{[extensibility docs](https://github.com/kyma-project/busola/tree/main/docs/extensibility)}}."
    }
