name: Busola Web Build

on:
  push:
    branches:
      - main
    paths:
      - "busola-frotnend-build.yml"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "../../Dockerfile.web"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - "busola-frotnend-build.yml"
      - "kyma/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "Makefile"
      - "../../Dockerfile.web"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-web-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: busola-frontend
      dockerfile: Dockerfile.web
      context: .
      export-tags: true
      tags: latest
