name: PR Lint Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  run-lint-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge with latest main
        uses: ./.github/actions/merge
      - name: lint_check
        shell: bash
        run: |
          set -e
          npm ci
          npm run eslint-check
          npm run lint-check
